### ISSUE TITLE
Acesso material (caderno)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa-aluno#9]
Link: https://alunos.educamaisdev.com/book/view/17
Descrição: ao tentar acessar um material pelo usuário de aluno, você é redirecionado para uma tela branca.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/230480161-6e163c1f-a351-4991-90a1-2e8ca59d16b9.png)

**Comment by flespindola** [comment]
Aqui funcionou. Verifica novamente por favor

<img width="1440" alt="Captura de Tela 2023-04-10 às 23 42 29" src="https://user-images.githubusercontent.com/95312656/231012711-6e6597e5-169b-4e69-8f75-4fdd52c0624a.png">

**Comment by RodolfoXYZ** [comment]
Mesma coisa, não estou conseguindo acessar o PDF que foi inserido no caderno, sempre redirecionado para uma tela branca

**Comment by flespindola** [comment]
É como se o arquivo tivesse vazio, foi algum bug talvez do servidor. Tenta mudar esse arquivo, enviar outro para ver se continua

**Comment by RodolfoXYZ** [comment]
Funcionou.
